#define Getting_Started 10
#define Save__addin_ 27
#define Open 11
#define Save 12
#define Add 14
#define Save_As 13
#define Remove 15
#define Convert 16
#define Exit 17
#define File_Names 18
#define Opening_ViewWorks_Files 19
#define Install_Uninstall 20
#define Machine_ID 21
#define Code 22
#define Registration 23
#define Known_Bugs_or_Problems 24
#define Issues 25
#define About 26
