// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// C++ TLBWRTR : $Revision:   1.134.1.39  $
// File generated on 6/30/00 10:12:39 PM from Type Library described below.

// ************************************************************************ //
// Type Lib: C:\Wombat\Pro\DMS_Unfg\DMS_Unfg.dll (1)
// IID\LCID: {0698F655-4EA6-11D4-8A0A-0020AFCC5695}\0
// Helpfile: 
// DepndLst: 
//   (1) v2.0 stdole, (C:\WINNT\System32\STDOLE2.TLB)
//   (2) v4.0 StdVCL, (C:\WINNT\System32\STDVCL40.DLL)
// ************************************************************************ //
#ifndef   __DMS_Unfg_OCX_h__
#define   __DMS_Unfg_OCX_h__

#pragma option push -b -w-inl

#include <utilcls.h>
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0500)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "DMS_Unfg_TLB.h"
namespace Dms_unfg_tlb
{

// *********************************************************************//
// HelpString: DMS_Unfg Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TDMS_Unfrag
// Help String      : DMS_Unfrag Object
// Default Interface: IDMS_Unfrag
// Def. Intf. Object: IDMS_UnfragPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TDMS_Unfrag : public Oleserver::TOleServer
{
  IDMS_UnfragPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TDMS_Unfrag(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IDMS_UnfragPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IDMS_UnfragPtr intf);


  void __fastcall Set_AuthCode(BSTR Param1/*[in]*/)
  {
    GetDefaultInterface()->set_AuthCode(Param1/*[in]*/);
  }

  int __fastcall Get_TimeOut(void)
  {
    return GetDefaultInterface()->get_TimeOut();
  }

  void __fastcall Set_TimeOut(int nTimeOut/*[in]*/)
  {
    GetDefaultInterface()->set_TimeOut(nTimeOut/*[in]*/);
  }

  int __fastcall Get_IsRegistered(void)
  {
    return GetDefaultInterface()->get_IsRegistered();
  }

  void __fastcall UnfragFile(BSTR sFileName/*[in]*/, long* nBytesSaved/*[out]*/)
  {
    GetDefaultInterface()->UnfragFile(sFileName/*[in]*/, nBytesSaved/*[out]*/);
  }

  void __fastcall RemovePreview(BSTR sFileName/*[in]*/)
  {
    GetDefaultInterface()->RemovePreview(sFileName/*[in]*/);
  }

  void __fastcall RemoveGeometry(BSTR sFileName/*[in]*/)
  {
    GetDefaultInterface()->RemoveGeometry(sFileName/*[in]*/);
  }

  __property BSTR AuthCode={ write=Set_AuthCode };
  __property int IsRegistered={ read=Get_IsRegistered };
  __property int TimeOut={ read=Get_TimeOut, write=Set_TimeOut, stored=false };
};

};     // namespace Dms_unfg_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Dms_unfg_tlb;
#endif

#pragma option pop

#endif // __DMS_Unfg_OCX_h__
