[InstallSHIELD Silent]
Version=v3.00.00
File=Response File
[DlgOrder]
Dlg0=Welcome-0
Dlg1=SdLicense-0
Dlg2=SdShowInfoList-0
Dlg3=AskDestPath-0
Dlg4=SdSelectFolder-0
Dlg5=SdStartCopy-0
Dlg6=SdFinish-0
Count=7
[Welcome-0]
Result=1
[SdLicense-0]
Result=1
[SdShowInfoList-0]
Result=1
[AskDestPath-0]
szPath=<ProgramFilesDir>\SolidPartners\SpellWorks
Result=1
[SdSelectFolder-0]
Result=1
szFolder=SpellWorks
[SdStartCopy-0]
Result=1
[SdFinish-0]
Result=1
bOpt1=0
bOpt2=0
